Repository pyp8s/pyp8s, pull requests merged in 2023-02, with the labels that each got.

#1 [Add] Release workflow implemented
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  Makefile
Labels: enhancement

#5 [Change] Additional labels support implemented
  README.md
  pyp8s/_version.py
  pyp8s/metrics.py
  tests/test_import.py
Labels: documentation, enhancement

#6 [Fix] Metric set was incorrectly accessing the existing metric.
  pyp8s/_version.py
  pyp8s/metrics.py
Labels: bug

#7 [Change] Sort of proper multi-metric implementation
  README.md
  pyp8s/_version.py
  pyp8s/metrics.py
  tests/test_import.py
Labels: documentation, enhancement
